#target aftereffects
#targetengine "SceneTrack"
#include "lib.jsx"
(function(thisObj){
    var root=typeof SCENETRACK_ROOT!=="undefined"?Folder(SCENETRACK_ROOT):File($.fileName).parent.parent,job=null,data=null,model=null,session=null,source=null,selected={},previewImage=null,observations=[],currentFrame=0,pollID=null,samBox=null,dragStart=null,sourceMeta=null,samPrompts={},promptFrame=0;
    var win=(thisObj instanceof Panel)?thisObj:new Window('palette','SceneTrack',undefined,{resizeable:true});
    win.orientation='column';win.alignChildren=['fill','top'];win.spacing=8;win.margins=12;
    win.add('statictext',undefined,'SceneTrack  /  3D camera tracking');
    var sourceRow=win.add('group');var pick=sourceRow.add('button',undefined,'Choose Footage');var fromLayer=sourceRow.add('button',undefined,'Use Selected Layer');
    var sourceLabel=win.add('statictext',undefined,'Choose a source clip. All processing stays on this Mac.',{truncate:'middle'});
    var rangeRow=win.add('group');rangeRow.add('statictext',undefined,'Frames');var start=rangeRow.add('edittext',undefined,'0');start.characters=6;rangeRow.add('statictext',undefined,'to');var end=rangeRow.add('edittext',undefined,'');end.characters=6;rangeRow.add('statictext',undefined,'(blank = end)');
    var options=win.add('group');var ai=options.add('checkbox',undefined,'AI exclusion masks');ai.value=true;options.add('statictext',undefined,'Gamma');var gamma=options.add('edittext',undefined,'1.8');gamma.characters=4;
    var backendRow=win.add('group');backendRow.add('statictext',undefined,'Mask model');var backend=backendRow.add('dropdownlist',undefined,['SAM 2.1 Tiny + text','Apple Vision people + text']);backend.selection=0;var previewButton=backendRow.add('button',undefined,'Preview Start');
    var promptRow=win.add('group');promptRow.add('statictext',undefined,'Correction frame');var correctionFrame=promptRow.add('edittext',undefined,'0');correctionFrame.characters=6;var correctionButton=promptRow.add('button',undefined,'Show Frame');
    var exitRow=win.add('group');exitRow.add('statictext',undefined,'Last frame with subject');var exitFrame=exitRow.add('edittext',undefined,'');exitFrame.characters=6;exitRow.add('statictext',undefined,'blank = entire range');
    var guardBoxes=win.add('checkbox',undefined,'Also exclude prompt boxes between corrections');guardBoxes.value=false;guardBoxes.helpTip='Conservative protection when SAM drifts under titles or occlusion. Review that boxes contain the subject.';
    var lens=win.add('group');lens.add('statictext',undefined,'Focal length (pixels)');var focal=lens.add('edittext',undefined,'');focal.characters=8;lens.add('statictext',undefined,'blank = estimate');
    var ex=win.add('edittext',undefined,'');ex.helpTip='Optional exclude rectangles: x0,y0,x1,y1 in 0–1 coordinates; separate rectangles with semicolons.';win.add('statictext',undefined,'Extra exclusions: x0,y0,x1,y1; ... (optional)');
    var actions=win.add('group');var analyze=actions.add('button',undefined,'Analyze Camera');var cancel=actions.add('button',undefined,'Cancel');cancel.enabled=false;var load=actions.add('button',undefined,'Open Solve…');
    var progress=win.add('progressbar',undefined,0,100);var status=win.add('statictext',undefined,'Ready.',{multiline:true});status.preferredSize.height=42;
    var modelSelect=win.add('dropdownlist');var ranges=win.add('dropdownlist');
    var canvas=win.add('panel');canvas.preferredSize=[480,270];canvas.minimumSize=[300,169];
    var scrub=win.add('slider',undefined,0,0,1);var frameLabel=win.add('statictext',undefined,'Click points to select. Shift-click adds to selection.');
    var stats=win.add('statictext',undefined,'',{multiline:true});stats.preferredSize.height=45;
    var out=win.add('group');var camera=out.add('button',undefined,'Create Camera');var nulls=out.add('button',undefined,'Create Nulls');var solid=out.add('button',undefined,'Create Solid');
    var notes=win.add('statictext',undefined,'Creates a new review composition. The source and existing cameras are preserved.',{multiline:true});notes.preferredSize.height=42;
    var redrawing=false;function redraw(){if(redrawing)return;redrawing=true;try{canvas.visible=false;canvas.visible=true;if(win instanceof Window)win.update();}finally{redrawing=false;}}
    function safe(fn){return function(){try{fn();}catch(e){status.text=e.toString();alert('SceneTrack\n'+e.toString());}};}
    function previewStart(frame){if(!source)return;promptFrame=typeof frame==='number'?frame:Number(start.text);if(!isFinite(promptFrame)||promptFrame<Number(start.text))throw Error('Choose a frame within the solve range.');promptFrame=Number(start.text)+Math.round((promptFrame-Number(start.text))/4)*4;correctionFrame.text=String(promptFrame);var folder=Folder(root.fsName+'/jobs');if(!folder.exists)folder.create();var file=File(folder.fsName+'/preview-'+new Date().getTime()+'.jpg');var response=system.callSystem(SceneTrack.quote(root.fsName+'/.venv/bin/python')+' '+SceneTrack.quote(root.fsName+'/worker/preview.py')+' '+SceneTrack.quote(source.fsName)+' '+SceneTrack.quote(String(promptFrame))+' '+SceneTrack.quote(file.fsName));sourceMeta=SceneTrack.parse(response);previewImage=ScriptUI.newImage(file);model=null;data=null;session=null;observations=[];samBox=samPrompts[String(promptFrame)]||null;frameLabel.text='Drag a box around the moving subject. SAM follows it through the shot.';redraw();}
    function setSource(file){source=file;sourceLabel.text=file.fsName;samPrompts={};exitFrame.text='';start.text='0';end.text='';previewStart();}
    previewButton.onClick=safe(function(){previewStart();});correctionButton.onClick=safe(function(){previewStart(Number(correctionFrame.text));});
    pick.onClick=safe(function(){var file=File.openDialog('Select footage');if(file)setSource(file);});
    fromLayer.onClick=safe(function(){var comp=app.project.activeItem;if(!(comp instanceof CompItem)||comp.selectedLayers.length!==1)throw Error('Select one footage layer.');var layer=comp.selectedLayers[0];if(!layer.source||!layer.source.file)throw Error('Select the original footage inside the precomposition, or use Choose Footage.');if(layer.timeRemapEnabled||layer.stretch!==100)throw Error('Use the original clip; retimed layers require a rendered copy.');setSource(layer.source.file);start.text=String(Math.max(0,Math.round((Math.max(comp.workAreaStart,layer.inPoint)-layer.startTime)*layer.source.frameRate)));end.text=String(Math.min(Math.round(layer.source.duration*layer.source.frameRate)-1,Math.ceil((Math.min(comp.workAreaStart+comp.workAreaDuration,layer.outPoint)-layer.startTime)*layer.source.frameRate)-1));previewStart();});
    function selectedPoints(){var pts=[];if(model)for(var i=0;i<model.points.length;i++)if(selected['p'+model.points[i].id])pts.push(model.points[i]);return pts;}
    function refresh(){if(!model)return;var p=model.poses[Math.round(scrub.value)];currentFrame=p.frame;previewImage=ScriptUI.newImage(File(job.fsName+'/frames/'+('000000'+currentFrame).slice(-6)+'.jpg'));observations=[];for(var i=0;i<model.observations.length;i++)if(model.observations[i].frame===currentFrame){observations=model.observations[i].points;break;}frameLabel.text='Frame '+currentFrame+'  ·  '+p.inliers+' inliers  ·  '+p.error_px.toFixed(2)+' px residual  ·  '+selectedPoints().length+' selected';if(session&&isValid(session.comp))session.comp.time=p.time;redraw();}
    canvas.onDraw=function(){var g=this.graphics,w=this.size.width,h=this.size.height;g.newPath();g.rectPath(0,0,w,h);g.fillPath(g.newBrush(g.BrushType.SOLID_COLOR,[.08,.08,.08,1]));if(!previewImage)return;g.drawImage(previewImage,0,0,w,h);if(samBox&&!model){g.newPath();g.rectPath(samBox[0]*w,samBox[1]*h,(samBox[2]-samBox[0])*w,(samBox[3]-samBox[1])*h);g.strokePath(g.newPen(g.PenType.SOLID_COLOR,[1,.7,.15,1],2));}if(!data)return;for(var i=0;i<observations.length;i++){var o=observations[i],x=o.uv[0]/data.metadata.width*w,y=o.uv[1]/data.metadata.height*h;var on=selected['p'+o.id];g.newPath();g.ellipsePath(x-3,y-3,6,6);g.strokePath(g.newPen(g.PenType.SOLID_COLOR,on?[1,.7,.15,1]:[.2,1,.55,1],on?2:1));}};
    canvas.addEventListener('mousedown',function(event){if(!model){if(previewImage){dragStart=[event.clientX/canvas.size.width,event.clientY/canvas.size.height];}return;}var best=null,dist=12;for(var i=0;i<observations.length;i++){var o=observations[i],dx=o.uv[0]/data.metadata.width*canvas.size.width-event.clientX,dy=o.uv[1]/data.metadata.height*canvas.size.height-event.clientY,d=Math.sqrt(dx*dx+dy*dy);if(d<dist){best=o.id;dist=d;}}if(!event.shiftKey)selected={};if(best!==null)selected['p'+best]=!selected['p'+best];refresh();});
    canvas.addEventListener('mousemove',function(event){if(!dragStart)return;var x=Math.max(0,Math.min(1,event.clientX/canvas.size.width)),y=Math.max(0,Math.min(1,event.clientY/canvas.size.height));samBox=[Math.min(x,dragStart[0]),Math.min(y,dragStart[1]),Math.max(x,dragStart[0]),Math.max(y,dragStart[1])];redraw();});
    canvas.addEventListener('mouseup',function(){if(dragStart){dragStart=null;if(samBox){samPrompts[String(promptFrame)]=samBox;}frameLabel.text='Prompt saved at frame '+promptFrame+'. Add a correction after large appearance changes.';}});
    scrub.onChanging=safe(refresh);
    function chooseModel(){model=data.models[modelSelect.selection.index];session=null;selected={};ranges.removeAll();var longest=0;for(var i=0;i<model.ranges.length;i++){var r=model.ranges[i];ranges.add('item','Frames '+r[0]+'–'+r[1]+' ('+((r[1]-r[0]+1)/data.metadata.fps).toFixed(2)+' s)');if(r[1]-r[0]>model.ranges[longest][1]-model.ranges[longest][0])longest=i;}ranges.selection=longest;scrub.minvalue=0;scrub.maxvalue=Math.max(1,model.poses.length-1);scrub.value=0;stats.text=model.summary.points+' points · '+(100*model.summary.coverage_fraction).toFixed(1)+'% coverage · median '+model.summary.median_error_px.toFixed(2)+' px\nAI masks improve feature selection; a full-clip solve is not guaranteed.';notes.text=data.warnings.join('\n');refresh();}
    modelSelect.onChange=safe(chooseModel);
    function openResult(file){var compact=File(file.parent.fsName+'/panel.json');if(file.name==='result.json'&&compact.exists)file=compact;data=SceneTrack.validate(SceneTrack.read(file));job=file.parent;modelSelect.removeAll();for(var i=0;i<data.models.length;i++)modelSelect.add('item','Model '+data.models[i].id+' · '+data.models[i].summary.solved_frames+' checked frames');modelSelect.selection=0;chooseModel();}
    load.onClick=safe(function(){var file=File.openDialog('Open SceneTrack result.json');if(file)openResult(file);});
    function tick(){try{if(!job)return;var file=File(job.fsName+'/status.json');if(file.exists){var s=SceneTrack.read(file);status.text=s.message;progress.value=s.progress;if(s.stage==='complete'||s.stage==='failed'||s.stage==='cancelled'){analyze.enabled=true;cancel.enabled=false;if(s.stage==='complete')openResult(File(job.fsName+'/result.json'));return;}}pollID=app.scheduleTask('SceneTrackPoll()',1000,false);}catch(e){status.text=e.toString();analyze.enabled=true;cancel.enabled=false;}}
    $.global.SceneTrackPoll=tick;
    analyze.onClick=safe(function(){if(!source||!source.exists)throw Error('Choose an available source clip.');var python=File(root.fsName+'/.venv/bin/python');if(!python.exists||!File(root.fsName+'/build/masker').exists)throw Error('Run scripts/setup.sh in the SceneTrack folder first.');var config={source:source.fsName,start_frame:Number(start.text),stride:4,width:960,gamma:Number(gamma.text),ai_masks:ai.value,exclude_rects:[]};if(!isFinite(config.start_frame)||config.start_frame<0||Math.floor(config.start_frame)!==config.start_frame)throw Error('Start must be a whole frame.');if(end.text!==''){config.end_frame=Number(end.text);if(!isFinite(config.end_frame)||config.end_frame<=config.start_frame||Math.floor(config.end_frame)!==config.end_frame)throw Error('End must be a whole frame after start.');}if(!isFinite(config.gamma)||config.gamma<.5||config.gamma>4)throw Error('Gamma must be 0.5–4.');if(focal.text!==''){config.focal_px=Number(focal.text);if(!isFinite(config.focal_px)||config.focal_px<=0)throw Error('Focal length must be a positive pixel value.');}if(ai.value&&backend.selection.index===0){var initialBox=samPrompts[String(config.start_frame)];if(!initialBox||initialBox[2]-initialBox[0]<.01||initialBox[3]-initialBox[1]<.01)throw Error('Click Preview Start and drag a box around the moving subject.');if(!File(root.fsName+'/models/sam2.1_hiera_tiny.pt').exists)throw Error('Run scripts/setup_sam.sh first.');config.mask_backend='sam2';config.sam_box=initialBox;config.sam_prompts=samPrompts;config.guard_prompt_boxes=guardBoxes.value;if(exitFrame.text!==''){config.subject_end_frame=Number(exitFrame.text);if(!isFinite(config.subject_end_frame)||Math.floor(config.subject_end_frame)!==config.subject_end_frame||config.subject_end_frame<config.start_frame)throw Error('Last subject frame must be a whole frame within the solve range.');}}if(ex.text!==''){var boxes=ex.text.split(';');for(var i=0;i<boxes.length;i++){var raw=boxes[i].split(','),box=[];if(raw.length!==4)throw Error('Each exclusion needs four coordinates.');for(var k=0;k<4;k++){var value=Number(raw[k]);if(!isFinite(value)||value<0||value>1)throw Error('Exclusion coordinates must be between 0 and 1.');box.push(value);}if(box[2]<=box[0]||box[3]<=box[1])throw Error('Exclusion rectangle is reversed.');config.exclude_rects.push(box);}}
        var jobs=Folder(root.fsName+'/jobs');if(!jobs.exists&&!jobs.create())throw Error('Cannot create jobs folder.');job=Folder(jobs.fsName+'/ae-'+new Date().getTime()+'-'+Math.floor(Math.random()*10000));if(!job.create())throw Error('Cannot create job folder.');SceneTrack.write(job.fsName+'/config.json',config);SceneTrack.write(job.fsName+'/status.json',{stage:'queued',progress:0,message:'Starting local worker…'});var response=system.callSystem(SceneTrack.quote(python.fsName)+' '+SceneTrack.quote(root.fsName+'/worker/launch.py')+' '+SceneTrack.quote(job.fsName));var info=SceneTrack.parse(response);if(!info.pid)throw Error('Worker did not start: '+response);analyze.enabled=false;cancel.enabled=true;status.text='Starting…';tick();});
    cancel.onClick=safe(function(){if(job){SceneTrack.write(job.fsName+'/cancel',{});status.text='Cancellation requested…';}});
    camera.onClick=safe(function(){if(!model||!ranges.selection)throw Error('Open a completed solve first.');session=SceneTrack.importCamera(data,model,model.ranges[ranges.selection.index]);status.text='Camera created in a new review composition. Select preview points to create nulls or a surface.';});
    nulls.onClick=safe(function(){SceneTrack.createNulls(session,selectedPoints());});solid.onClick=safe(function(){SceneTrack.createSolid(session,selectedPoints());});
    if(typeof SCENETRACK_TEST!=='undefined'&&SCENETRACK_TEST){$.global.SceneTrackTest={source:setSource,open:openResult,createCamera:function(){camera.onClick();},select:function(ids){selected={};for(var j=0;j<ids.length;j++)selected['p'+ids[j]]=true;refresh();},createNulls:function(){nulls.onClick();},createSolid:function(){solid.onClick();},get:function(){return {window:win,source:source,preview:previewImage,model:model,session:session,status:status.text};}};}
    win.onResizing=win.onResize=function(){this.layout.resize();redraw();};win.onClose=function(){if(pollID)app.cancelTask(pollID);};win.layout.layout(true);if(win instanceof Window){win.center();win.show();}
})(this);
